### ISSUE TITLE
Lesson 1-2

### ISSUE THREAD

**Issue by bobuskiy** [Sjan73/Sjan73.github.io#1]
Помню тут был первый раз не зачет 21.10.2015

**Comment by Sjan73** [comment]
я редагував репозиторій, тощу що документ не відкривався в браузері

**Comment by bobuskiy** [comment]
Незачет!
У блока с классом container убрать высоту!
Высоту можно задавать только некоторым елементам, но не для всей страницы. Если у нас будет больше контента, то дела будут плохи.

Где тень у основного блока? Добавить тень!

Немного отклонился от шаблона, но не критично.

Проверено 24.10.2015

**Comment by Sjan73** [comment]
Висоту забрав, тінь до основного блоку добавив.

**Comment by bobuskiy** [comment]
Зачет!
