### ISSUE TITLE
js 5-6

### ISSUE THREAD

**Issue by bobuskiy** [Sjan73/Sjan73.github.io#8]
незачет.

ресет не сбрасывает в ноль, а ставит в конце "1". и миллисекунды должны идти от 0 до 999

**Comment by Sjan73** [comment]
hours замінив через setHours(0); по ідеї тепер нормально  працює

**Comment by bobuskiy** [comment]
незачет.

clear має не лише обнуляти слайдер а ще і зупиняти. це коли таймер працює.

проверено 14.01.2016

**Comment by Sjan73** [comment]
Функцію reset повішав на clear, тепер обнуляє зразу

**Comment by bobuskiy** [comment]
зачет
